from django.db import models

# Create your models here.

class TestFIN005Raw(models.Model):
    PERIOD = models.CharField(max_length=255, default = None, blank=True, null=True)
    EMPLOYEE_NUMBER = models.CharField(max_length=255, default = None, null=True)
    EMPLOYEE_NAME = models.CharField(max_length=255, default = None, null=True)
    SUPPLEMENTAL_PAY_TYPE = models.CharField(max_length=255, default = None, blank=True, null=True)
    CLAIM_MONTH = models.CharField(max_length=255, default = None, blank=True, null=True)
    CLAIM_DATE = models.CharField(max_length=255, default = None, blank=True, null=True)
    REGULAR_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    OT_TIME_IN = models.CharField(max_length=255, default = None, blank=True, null=True)
    OT_TIME_OUT = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_OT_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    OVERTIME_TIME_AMT_PAY = models.CharField(max_length=255, default = None, blank=True, null=True)
    STANDBY_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    STNDBY_AMT = models.CharField(max_length=255, default = None, blank=True, null=True)
    SHIFT_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    SHIFT_AMT = models.CharField(max_length=255, default = None, blank=True, null=True)
    SHIFT_AMT = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_PAYOUT_PHP = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_PAYOUT_USD = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_PAYOUT_PERCENT = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True)
    COMMENTS = models.CharField(max_length=255, default = None, blank=True, null=True)
    PRJ_CUSTOMER = models.CharField(max_length=255, default = None, blank=True, null=True)
    PRJ_CUSTOMER2 = models.CharField(max_length=255, default = None, blank=True, null=True)
    PROJECT = models.CharField(max_length=255, default = None, blank=True, null=True)
    PROJECT2 = models.CharField(max_length=255, default = None, blank=True, null=True)
    WBS = models.CharField(max_length=255, default = None, blank=True, null=True)
    WBS_DESCRIPTION = models.CharField(max_length=255, default = None, blank=True, null=True)
    DCL_FINAL = models.CharField(max_length=255, default = None, blank=True, null=True)
    LOCATION_CODE = models.CharField(max_length=255, default = None, blank=True, null=True)
    MANAGER_ID = models.CharField(max_length=255, default = None, blank=True, null=True)
    MANAGER_NAME = models.CharField(max_length=255, default = None, blank=True, null=True)
    MODIFIED = models.CharField(max_length=255, default = None, blank=True, null=True)
    
class TempFIN005Raw(models.Model):
    PERIOD = models.DateTimeField(blank=True, null=True)
    EMPLOYEE_NUMBER = models.CharField(max_length=255, default = None, blank=True, null=True)
    EMPLOYEE_NAME = models.CharField(max_length=255, default = None, blank=True, null=True)
    SUPPLEMENTAL_PAY_TYPE = models.CharField(max_length=255, default = None, blank=True, null=True)
    CLAIM_MONTH = models.CharField(max_length=255, default = None, blank=True, null=True)
    CLAIM_DATE = models.DateTimeField(blank=True, null=True)
    REGULAR_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    OT_TIME_IN = models.DateTimeField(blank=True, null=True)
    OT_TIME_OUT = models.DateTimeField(blank=True, null=True)
    TOTAL_OT_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    OVERTIME_TIME_AMT_PAY = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    STANDBY_HOURS = models.DecimalField(max_digits=22, decimal_places=10, null=True)
    STNDBY_AMT = models.DecimalField(max_digits=22, decimal_places=10, null=True)
    SHIFT_HOURS = models.DecimalField(max_digits=22, decimal_places=10, null=True)
    SHIFT_AMT = models.DecimalField(max_digits=22, decimal_places=10, null=True)
    TOTAL_PAYOUT_PHP = models.DecimalField(max_digits=22, decimal_places=10, null=True)
    TOTAL_PAYOUT_USD = models.DecimalField(max_digits=22, decimal_places=10, null=True)
    TOTAL_PAYOUT_PERCENT = models.DecimalField(max_digits=10, decimal_places=5)
    COMMENTS = models.CharField(max_length=255, default = None, blank=True, null=True)
    PRJ_CUSTOMER = models.CharField(max_length=255, default = None, blank=True, null=True)
    PRJ_CUSTOMER2 = models.CharField(max_length=255, default = None, blank=True, null=True)
    PROJECT = models.CharField(max_length=255, default = None, blank=True, null=True)
    PROJECT2 = models.CharField(max_length=255, default = None, blank=True, null=True)
    WBS = models.CharField(max_length=255, default = None, blank=True, null=True)
    WBS_DESCRIPTION = models.CharField(max_length=255, default = None, blank=True, null=True)
    DCL_FINAL = models.CharField(max_length=255, default = None, blank=True, null=True)
    LOCATION_CODE = models.CharField(max_length=255, default = None, blank=True, null=True)
    MANAGER_ID = models.CharField(max_length=255, default = None, blank=True, null=True)
    MANAGER_NAME = models.CharField(max_length=255, default = None, blank=True, null=True)
    MODIFIED = models.CharField(max_length=255, default = None, blank=True, null=True)

class META_SHIFT(models.Model):
    id = models.IntegerField
    sheetNames = models.CharField(max_length=255)
    colNames = models.CharField(max_length=500)
    fileName = models.CharField(max_length=255)
    fileType = models.CharField(max_length=255)
    numberOfColumns = models.IntegerField()
