# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='META_SHIFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetNames', models.CharField(max_length=255)),
                ('colNames', models.CharField(max_length=500)),
                ('fileName', models.CharField(max_length=255)),
                ('fileType', models.CharField(max_length=255)),
                ('numberOfColumns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('target_schema', models.CharField(max_length=255)),
                ('target_table', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_COLS',
            fields=[
                ('column_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dataType', models.CharField(max_length=255)),
                ('isRequired', models.CharField(default='N', max_length=1)),
                ('default', models.CharField(default='N', max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('uploader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.MTDTA_UPLOADER')),
            ],
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_PARAMS',
            fields=[
                ('parameter_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dataType', models.CharField(max_length=255)),
                ('isRequired', models.CharField(default='N', max_length=1)),
                ('default', models.CharField(default='N', max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('uploader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.MTDTA_UPLOADER')),
            ],
        ),
        migrations.CreateModel(
            name='TestFIN005Raw',
            fields=[
                ('id', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('PERIOD', models.CharField(default='', max_length=255)),
                ('EMPLOYEE_NUMBER', models.CharField(default='', max_length=255)),
                ('EMPLOYEE_NAME', models.CharField(default='', max_length=255)),
                ('SUPPLEMENTAL_PAY_TYPE', models.CharField(default='', max_length=255)),
                ('CLAIM_MONTH', models.CharField(default='', max_length=255)),
                ('CLAIM_DATE', models.CharField(default='', max_length=255)),
                ('IS_LATE_FILING', models.CharField(default='', max_length=255)),
                ('REGULAR_HOURS', models.CharField(default='', max_length=255)),
                ('OT_TIME_IN', models.CharField(default='', max_length=255)),
                ('OT_TIME_OUT', models.CharField(default='', max_length=255)),
                ('TOTAL_OT_HOURS', models.CharField(default='', max_length=255)),
                ('OVERTIME_TIME_AMT_PAY', models.CharField(default='', max_length=255)),
                ('STANDBY_HOURS', models.CharField(default='', max_length=255)),
                ('STNDBY_AMT', models.CharField(default='', max_length=255)),
                ('SHIFT_HOURS', models.CharField(default='', max_length=255)),
                ('SHIFT_AMT', models.CharField(default='', max_length=255)),
                ('TOTAL_PAYOUT_PHP', models.CharField(default='', max_length=255)),
                ('TOTAL_PAYOUT_USD', models.CharField(default='', max_length=255)),
                ('TOTAL_PAYOUT_PERCENT', models.CharField(default='', max_length=255)),
                ('COMMENTS', models.CharField(default='', max_length=255)),
                ('PRJ_CUSTOMER', models.CharField(default='', max_length=255)),
                ('PRJ_CUSTOMER2', models.CharField(default='', max_length=255)),
                ('PROJECT', models.CharField(default='', max_length=255)),
                ('PROJECT2', models.CharField(default='', max_length=255)),
                ('WBS', models.CharField(default='', max_length=255)),
                ('WBS_DESCRIPTION', models.CharField(default='', max_length=255)),
                ('DCL_FINAL', models.CharField(default='', max_length=255)),
                ('LOCATION_CODE', models.CharField(default='', max_length=255)),
                ('MANAGER_ID', models.CharField(default='', max_length=255)),
                ('MANAGER_NAME', models.CharField(default='', max_length=255)),
                ('MODIFIED', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
