# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFIN005Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PERIOD', models.CharField(default='', max_length=255)),
                ('EMPLOYEE_NUMBER', models.CharField(default='', max_length=255)),
                ('EMPLOYEE_NAME', models.CharField(default='', max_length=255)),
                ('SUPPLEMENTAL_PAY_TYPE', models.CharField(default='', max_length=255)),
                ('CLAIM_MONTH', models.CharField(default='', max_length=255)),
                ('CLAIM_DATE', models.CharField(default='', max_length=255)),
                ('REGULAR_HOURS', models.CharField(default='', max_length=255)),
                ('OT_TIME_IN', models.CharField(default='', max_length=255)),
                ('OT_TIME_OUT', models.CharField(default='', max_length=255)),
                ('TOTAL_OT_HOURS', models.CharField(default='', max_length=255)),
                ('OVERTIME_TIME_AMT_PAY', models.CharField(default='', max_length=255)),
                ('STANDBY_HOURS', models.CharField(default='', max_length=255)),
                ('STNDBY_AMT', models.CharField(default='', max_length=255)),
                ('SHIFT_HOURS', models.CharField(default='', max_length=255)),
                ('SHIFT_AMT', models.CharField(default='', max_length=255)),
                ('TOTAL_PAYOUT_PHP', models.CharField(default='', max_length=255)),
                ('TOTAL_PAYOUT_USD', models.CharField(default='', max_length=255)),
                ('TOTAL_PAYOUT_PERCENT', models.DecimalField(decimal_places=5, max_digits=10)),
                ('COMMENTS', models.CharField(default='', max_length=255)),
                ('PRJ_CUSTOMER', models.CharField(default='', max_length=255)),
                ('PRJ_CUSTOMER2', models.CharField(default='', max_length=255)),
                ('PROJECT', models.CharField(default='', max_length=255)),
                ('PROJECT2', models.CharField(default='', max_length=255)),
                ('WBS', models.CharField(default='', max_length=255)),
                ('WBS_DESCRIPTION', models.CharField(default='', max_length=255)),
                ('DCL_FINAL', models.CharField(default='', max_length=255)),
                ('LOCATION_CODE', models.CharField(default='', max_length=255)),
                ('MANAGER_ID', models.CharField(default='', max_length=255)),
                ('MANAGER_NAME', models.CharField(default='', max_length=255)),
                ('MODIFIED', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
