# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtdta_uploader_cols',
            name='uploader_id',
        ),
        migrations.RemoveField(
            model_name='mtdta_uploader_params',
            name='uploader_id',
        ),
        migrations.DeleteModel(
            name='MTDTA_UPLOADER',
        ),
        migrations.DeleteModel(
            name='MTDTA_UPLOADER_COLS',
        ),
        migrations.DeleteModel(
            name='MTDTA_UPLOADER_PARAMS',
        ),
    ]
