# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_testfin005raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempfin005raw',
            name='CLAIM_MONTH',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='COMMENTS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='DCL_FINAL',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='EMPLOYEE_NAME',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='EMPLOYEE_NUMBER',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='LOCATION_CODE',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='MANAGER_ID',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='MANAGER_NAME',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='MODIFIED',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='PRJ_CUSTOMER',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='PRJ_CUSTOMER2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='PROJECT',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='PROJECT2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='REGULAR_HOURS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='SUPPLEMENTAL_PAY_TYPE',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='TOTAL_OT_HOURS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='WBS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempfin005raw',
            name='WBS_DESCRIPTION',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='CLAIM_DATE',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='CLAIM_MONTH',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='COMMENTS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='DCL_FINAL',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='EMPLOYEE_NAME',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='EMPLOYEE_NUMBER',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='LOCATION_CODE',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='MANAGER_ID',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='MANAGER_NAME',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='MODIFIED',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='OT_TIME_IN',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='OT_TIME_OUT',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='OVERTIME_TIME_AMT_PAY',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='PERIOD',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='PRJ_CUSTOMER',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='PRJ_CUSTOMER2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='PROJECT',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='PROJECT2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='REGULAR_HOURS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='SHIFT_AMT',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='SHIFT_HOURS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='STANDBY_HOURS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='STNDBY_AMT',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='SUPPLEMENTAL_PAY_TYPE',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='TOTAL_OT_HOURS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='TOTAL_PAYOUT_PHP',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='TOTAL_PAYOUT_USD',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='WBS',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testfin005raw',
            name='WBS_DESCRIPTION',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
