# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTDTA_UPLOADER',
            fields=[
                ('uploader', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='[name]-uploader', max_length=100)),
                ('description', models.CharField(default='File loader for ...', max_length=255)),
                ('source_path', models.CharField(default='\\pg_bizops\\FILE_UPLOADER\\[source folder]', max_length=255)),
                ('server', models.CharField(default='16.179.110.132', max_length=255)),
                ('file_name', models.CharField(default='', max_length=255)),
                ('file_type', models.CharField(default='.xlsx', max_length=255)),
                ('sheet_name', models.CharField(default='Sheet1', max_length=255)),
                ('delimiter', models.CharField(default=',', max_length=255)),
                ('start_row', models.IntegerField(default=0)),
                ('target_schema', models.CharField(default='FPD', max_length=255)),
                ('target_table', models.CharField(default='TMP_', max_length=255)),
                ('email_sender', models.CharField(default='pg_bizopssupport@hpe.com', max_length=255)),
                ('email_recipient', models.CharField(default='username@hpe.com', max_length=255)),
                ('email_cc', models.CharField(default='pg_bizopssupport@hpe.com', max_length=255)),
                ('last_update_uid', models.CharField(default='username@hpe.com', max_length=255)),
                ('last_update', models.DateField()),
            ],
            options={
                'managed': True,
                'db_table': 'MTDTA_UPLOADER',
            },
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_COLS',
            fields=[
                ('column', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='Column for ...', max_length=255)),
                ('is_required', models.CharField(default='N', max_length=1)),
                ('max_length', models.CharField(default='255', max_length=255)),
                ('default', models.CharField(default='None', max_length=255)),
                ('format', models.CharField(default='None', max_length=255)),
                ('last_update_uid', models.CharField(default='username@hpe.com', max_length=255)),
                ('last_update', models.DateField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MTDTA_UPLOADER')),
            ],
            options={
                'managed': True,
                'db_table': 'MTDTA_UPLOADER_COLS',
            },
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_PARAMS',
            fields=[
                ('parameter', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('is_required', models.CharField(default='N', max_length=1)),
                ('default_value', models.CharField(default='N', max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('last_update_uid', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MTDTA_UPLOADER')),
            ],
            options={
                'managed': True,
                'db_table': 'MTDTA_UPLOADER_PARAMS',
            },
        ),
    ]
