# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTDTA_UPLOADER',
            fields=[
                ('uploader', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('target_schema', models.CharField(max_length=255)),
                ('target_table', models.CharField(max_length=255)),
                ('last_update_uid', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_COLS',
            fields=[
                ('column', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('is_required', models.CharField(default='N', max_length=1)),
                ('default', models.CharField(default='N', max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('last_update_uid', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MTDTA_UPLOADER')),
            ],
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_PARAMS',
            fields=[
                ('parameter', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('is_required', models.CharField(default='N', max_length=1)),
                ('default_value', models.CharField(default='N', max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('last_update_uid', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MTDTA_UPLOADER')),
            ],
        ),
    ]
