# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTDTA_UPLOADER',
            fields=[
                ('uploader', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('target_schema', models.CharField(max_length=255)),
                ('target_table', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_COLS',
            fields=[
                ('column', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dataType', models.CharField(max_length=255)),
                ('isRequired', models.CharField(default='N', max_length=1)),
                ('default', models.CharField(default='N', max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MTDTA_UPLOADER')),
            ],
        ),
        migrations.CreateModel(
            name='MTDTA_UPLOADER_PARAMS',
            fields=[
                ('parameter', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dataType', models.CharField(max_length=255)),
                ('isRequired', models.CharField(default='N', max_length=1)),
                ('default', models.CharField(default='N', max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MTDTA_UPLOADER')),
            ],
        ),
    ]
