# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtdta_uploader',
            old_name='date_created',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='mtdta_uploader_cols',
            old_name='dataType',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='mtdta_uploader_cols',
            old_name='isRequired',
            new_name='is_required',
        ),
        migrations.RenameField(
            model_name='mtdta_uploader_cols',
            old_name='date_created',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='mtdta_uploader_params',
            old_name='dataType',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='mtdta_uploader_params',
            old_name='default',
            new_name='default_value',
        ),
        migrations.RenameField(
            model_name='mtdta_uploader_params',
            old_name='isRequired',
            new_name='is_required',
        ),
        migrations.RenameField(
            model_name='mtdta_uploader_params',
            old_name='date_created',
            new_name='last_update',
        ),
        migrations.AddField(
            model_name='mtdta_uploader',
            name='file_name',
            field=models.CharField(default='filename', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtdta_uploader',
            name='file_type',
            field=models.CharField(default='filetype', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtdta_uploader',
            name='last_update_uid',
            field=models.CharField(default='lastupdateuid', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtdta_uploader',
            name='sheet_name',
            field=models.CharField(default='sheetname', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtdta_uploader',
            name='source_path',
            field=models.CharField(default='sourcepath', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtdta_uploader_cols',
            name='last_update_uid',
            field=models.CharField(default='lastupdateuid', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtdta_uploader_params',
            name='last_update_uid',
            field=models.CharField(default='lastupdateuid', max_length=255),
            preserve_default=False,
        ),
    ]
