# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTL_FILE_LOADER_BOT_LOGS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploader_name', models.CharField(max_length=255)),
                ('last_update_uid', models.CharField(max_length=255)),
                ('update_start_timestamp', models.DateTimeField()),
                ('update_end_timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('error_details', models.CharField(max_length=4000, null=True)),
                ('warning_details', models.CharField(max_length=4000, null=True)),
                ('email_sent', models.CharField(max_length=255)),
                ('table_truncated', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'UTL_FILE_LOADER_BOT_LOGS',
                'managed': True,
            },
        ),
    ]
