# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170802_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtdta_uploader',
            name='email_cc',
            field=models.CharField(default='pg_bizopssupport@hpe.com', max_length=255),
        ),
        migrations.AddField(
            model_name='mtdta_uploader',
            name='email_recipient',
            field=models.CharField(default='username@hpe.com', max_length=255),
        ),
        migrations.AddField(
            model_name='mtdta_uploader',
            name='email_sender',
            field=models.CharField(default='pg_bizopssupport@hpe.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='description',
            field=models.CharField(default='File upload of ...', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='file_type',
            field=models.CharField(default='.xlsx', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='last_update_uid',
            field=models.CharField(default='username@hpe.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='name',
            field=models.CharField(default='[name]-uploader', max_length=100),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='server',
            field=models.CharField(default='16.179.110.132', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='sheet_name',
            field=models.CharField(default='Sheet1', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='source_path',
            field=models.CharField(default='\\pg_bizops\\FILE_UPLOADER\\[source folder]', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='target_schema',
            field=models.CharField(default='FPD', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='target_table',
            field=models.CharField(default='TMP_', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader_cols',
            name='data_type',
            field=models.CharField(default='str', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader_cols',
            name='description',
            field=models.CharField(default='Column for ...', max_length=255),
        ),
    ]
