# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170629_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtdta_uploader',
            name='server',
            field=models.CharField(default='a4pgbizopsdev.svcs.entsvcs.net', max_length=255),
            preserve_default=False,
        ),
    ]
