# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170804_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtdta_uploader',
            name='append_new',
            field=models.CharField(default='N', max_length=255),
        ),
    ]
