# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_mtdta_uploader_start_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtdta_uploader_cols',
            name='max_length',
            field=models.CharField(default='255', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='description',
            field=models.CharField(default='File loader for ...', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader_cols',
            name='default',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader_cols',
            name='format',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtdta_uploader_cols',
            name='last_update_uid',
            field=models.CharField(default='username@hpe.com', max_length=255),
        ),
    ]
