# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170818_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtdta_uploader',
            name='start_row',
            field=models.IntegerField(default=0),
        ),
    ]
