# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170818_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtdta_uploader_cols',
            name='data_type',
        ),
    ]
