from django.db import models

# Template for new temporary tables
# class TMP_[TEMPORARY_TABLE_NAME](models.Model):
#     [column_name] = models.CharField(max_length=255, default = None, blank=True, null=True)
#     [column_name] = models.DecimalField(max_digits=38, decimal_places=15, blank=True, null=True)

# shift temporary table
class shift_temp_table(models.Model):
    PERIOD = models.CharField(max_length=255, default = None, blank=True, null=True)
    EMPLOYEE_NUMBER = models.CharField(max_length=255, default = None, null=True)
    EMPLOYEE_NAME = models.CharField(max_length=255, default = None, null=True)
    SUPPLEMENTAL_PAY_TYPE = models.CharField(max_length=255, default = None, blank=True, null=True)
    CLAIM_MONTH = models.CharField(max_length=255, default = None, blank=True, null=True)
    CLAIM_DATE = models.CharField(max_length=255, default = None, blank=True, null=True)
    REGULAR_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    OT_TIME_IN = models.CharField(max_length=255, default = None, blank=True, null=True)
    OT_TIME_OUT = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_OT_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    OVERTIME_TIME_AMT_PAY = models.CharField(max_length=255, default = None, blank=True, null=True)
    STANDBY_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    STNDBY_AMT = models.CharField(max_length=255, default = None, blank=True, null=True)
    SHIFT_HOURS = models.CharField(max_length=255, default = None, blank=True, null=True)
    SHIFT_AMT = models.CharField(max_length=255, default = None, blank=True, null=True)
    SHIFT_AMT = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_PAYOUT_PHP = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_PAYOUT_USD = models.CharField(max_length=255, default = None, blank=True, null=True)
    TOTAL_PAYOUT_PERCENT = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True)
    COMMENTS = models.CharField(max_length=255, default = None, blank=True, null=True)
    PRJ_CUSTOMER = models.CharField(max_length=255, default = None, blank=True, null=True)
    PRJ_CUSTOMER2 = models.CharField(max_length=255, default = None, blank=True, null=True)
    PROJECT = models.CharField(max_length=255, default = None, blank=True, null=True)
    PROJECT2 = models.CharField(max_length=255, default = None, blank=True, null=True)
    WBS = models.CharField(max_length=255, default = None, blank=True, null=True)
    WBS_DESCRIPTION = models.CharField(max_length=255, default = None, blank=True, null=True)
    DCL_FINAL = models.CharField(max_length=255, default = None, blank=True, null=True)
    LOCATION_CODE = models.CharField(max_length=255, default = None, blank=True, null=True)
    MANAGER_ID = models.CharField(max_length=255, default = None, blank=True, null=True)
    MANAGER_NAME = models.CharField(max_length=255, default = None, blank=True, null=True)
    MODIFIED = models.CharField(max_length=255, default = None, blank=True, null=True)

# transition countries temporary table
class TMP_TRANSITION_COUNTRIES(models.Model):
    service_month = models.CharField(max_length=255, default = None, blank=True, null=True)
    manager_email = models.CharField(max_length=255, default = None, null=True)
    employee_id = models.CharField(max_length=255, default = None, null=True)
    employee_name = models.CharField(max_length=255, default = None, blank=True, null=True)
    employee_email = models.CharField(max_length=255, default = None, blank=True, null=True)
    pg_level = models.CharField(max_length=255, default = None, blank=True, null=True)
    daily_expected_hours = models.CharField(max_length=255, default = None, blank=True, null=True)
    employee_type = models.CharField(max_length=255, default = None, blank=True, null=True)
    bill_to_county = models.CharField(max_length=255, default = None, blank=True, null=True)
    geography = models.CharField(max_length=255, default = None, blank=True, null=True)
    hp_level = models.CharField(max_length=255, default = None, blank=True, null=True)
    seat_country_code = models.CharField(max_length=255, default = None, blank=True, null=True)
    seat_country = models.CharField(max_length=255, default = None, blank=True, null=True)
    wbs = models.CharField(max_length=255, default = None, blank=True, null=True)
    wbs_description = models.CharField(max_length=255, default = None, blank=True, null=True)
    aa_type = models.CharField(max_length=255, default = None, blank=True, null=True)
    attribute = models.CharField(max_length=255, default = None, blank=True, null=True)
    attribute_2 = models.CharField(max_length=255, default = None, blank=True, null=True)
    short_text = models.CharField(max_length=255, default = None, blank=True, null=True)
    hp_labor_rate = models.DecimalField(max_digits=38, decimal_places=15, blank=True, null=True)
    usd_labor_currency = models.DecimalField(max_digits=38, decimal_places=15, blank=True, null=True)
    hours = models.DecimalField(max_digits=38, decimal_places=15, blank=True, null=True)

